version: "3.4"

services:
  ch-remote:
    image: kai/ch-remote-dev:1.0
    build: .
    container_name: ch-remote-dev
    ports:
      - "127.0.0.1:2222:22"
      - "127.0.0.1:9015:9000"
      - "127.0.0.1:8115:8123"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /clickhouse:/home/ch-builder/clickhouse
      - /clickhouse/programs/server/config.xml:/etc/clickhouse-server/config.xml
      - /clickhouse/programs/server/users.xml:/etc/clickhouse-server/users.xml
      - ./ch-remote-dev/config.d:/etc/clickhouse-server/config.d
      - /data/log:/var/log/clickhouse-server
      - /data/cache:/var/lib/clickhouse/cache
    restart: unless-stopped
    networks:
      - ch-cluster
  ch-keeper-1:
    image: clickhouse/clickhouse-keeper:24.3.12.75-alpine
    container_name: keeper-server-1
    volumes:
      - ./ch-remote-dev/keeper-1:/etc/clickhouse-keeper
      - /data/keeper-1/log:/var/log/clickhouse-keeper
      - /data/keeper-1/data:/data
      - /data/keeper-1/datalog:/datalog
      - /data/keeper-1/datalog:/var/lib/clickhouse/coordination/log
      - /data/keeper-1/datalog:/var/lib/clickhouse/coordination/snapshots
    restart: unless-stopped
    networks:
      - ch-cluster
  ch-keeper-2:
    image: clickhouse/clickhouse-keeper:24.3.12.75-alpine
    container_name: keeper-server-2
    volumes:
      - /Users/nauu/CLionProjects/ch-remote-dev/keeper-2:/etc/clickhouse-keeper
      - /data/keeper-2/log:/var/log/clickhouse-keeper
      - /data/keeper-2/data:/data
      - /data/keeper-2/datalog:/datalog
      - /data/keeper-2/datalog:/var/lib/clickhouse/coordination/log
      - /data/keeper-2/datalog:/var/lib/clickhouse/coordination/snapshots
    restart: unless-stopped
    networks:
      - ch-cluster
networks:
  ch-cluster:
    external: true

#    docker network create "ch-cluster"